### ISSUE TITLE
Error on local deployment identity-tenant-manage

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/backend#29]
Log:
```
backend_1             | (node:1) ExperimentalWarning: The fs.promises API is experimental
backend_1             | SONO QUI
backend_1             | RSwAbICtX3kep6hsrGFw
backend_1             | { name: 'micadoDS',
backend_1             |   connector: 'postgresql',
backend_1             |   url: 'postgres://micadoapp:micadoapp@micado_db/micado',
backend_1             |   host: 'micado_db',
backend_1             |   port: 5432,
backend_1             |   user: 'micadoapp',
backend_1             |   password: 'process.env.MICADO_DB_PWD',
backend_1             |   schema: 'micadoapp',
backend_1             |   migrationCreateSchema: false,
backend_1             |   database: 'micado' }
backend_1             | { name: 'micadoDS',
backend_1             |   connector: 'postgresql',
backend_1             |   url: 'postgres://micadoapp:RSwAbICtX3kep6hsrGFw@micado_db/micado',
backend_1             |   host: 'micado_db',
backend_1             |   port: 5432,
backend_1             |   user: 'micadoapp',
backend_1             |   password: 'RSwAbICtX3kep6hsrGFw',
backend_1             |   schema: 'micadoapp',
backend_1             |   migrationCreateSchema: false,
backend_1             |   database: 'micado' }
backend_1             | Server is running at http://172.24.0.9:3000
backend_1             | Try http://172.24.0.9:3000/ping
backend_1             | in the identity controller retrieveTenants
backend_1             | IN RETRIEVE TENANT FUCNTION
backend_1             | prod
backend_1             | :9443
backend_1             | https://identity.micado.codeurjc.es:9443/services/TenantMgtAdminService?wsdl
backend_1             | /home/node/app/dist/controllers/identity-tenant-manager.controller.js:72
backend_1             |                 client.setSecurity(new soap.BasicAuthSecurity(process.env.WSO2_IDENTITY_ADMIN_USER, process.env.WSO2_IDENTITY_ADMIN_PWD));
backend_1             |                        ^
backend_1             |
backend_1             | TypeError: Cannot read property 'setSecurity' of undefined
backend_1             |     at /home/node/app/dist/controllers/identity-tenant-manager.controller.js:72:24
backend_1             |     at /home/node/app/node_modules/soap/lib/soap.js:84:9
backend_1             |     at /home/node/app/node_modules/soap/lib/soap.js:39:28
backend_1             |     at /home/node/app/node_modules/soap/lib/wsdl/index.js:1250:17
backend_1             |     at Request._callback (/home/node/app/node_modules/soap/lib/http.js:159:28)
backend_1             |     at self.callback (/home/node/app/node_modules/request/request.js:185:22)
backend_1             |     at Request.emit (events.js:198:13)
backend_1             |     at Request.onRequestError (/home/node/app/node_modules/request/request.js:877:8)
backend_1             |     at ClientRequest.emit (events.js:198:13)
backend_1             |     at TLSSocket.socketErrorListener (_http_client.js:392:9)
backend_1             |     at TLSSocket.emit (events.js:198:13)
backend_1             |     at emitErrorNT (internal/streams/destroy.js:91:8)
backend_1             |     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
backend_1             |     at process._tickCallback (internal/process/next_tick.js:63:19)```

**Comment by gioppoluca** [comment]
Probably fixed with the latest docker-compose-prod in deployment please download that one (there was a leftover of old micado names around)
